# Generated by Django 5.1 on 2024-08-26 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('description', models.TextField(help_text='Descrição da tarefa:', max_length=400)),
                ('completed', models.CharField(choices=[('concluído', 'Concluído'), ('pendente', 'Pendente')], default='Pendente', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(max_length=8)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
