# Generated by Django 5.1 on 2024-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.CharField(choices=[('concluído', 'Concluído'), ('pendente', 'Pendente')], default='pendente', max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
